name: Build PDF for Release

on:
    push:
        branches:
            - master # Only run on the master branch
        paths: 
            - '**.tex' # Only run if the resume itself is updated
        tags-ignore:
            - nochange**   # Do not build a new version for any commit tagged with a tag that starts with nochange
    workflow_dispatch:
        
                
            

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y texlive-xetex
                  
            - name: Build Document
              run: xelatex Gabriel_Roper_Resume.tex

            - name: Get Current DateTime
              id: getdate
              run: echo "::set-output name=dtVal::$(date +'%Y-%m-%d_%H.%M')"

            - name: Create Release
              uses: actions/create-release@v1
              id: create_release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                  tag_name: ${{steps.getdate.outputs.dtVal}}
                  release_name: Resume ${{steps.getdate.outputs.dtVal}}
                  draft: false
                  prerelease: false

            - name: Add resume PDF
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./Gabriel_Roper_Resume.pdf
                  asset_name: Gabriel_Roper_Resume.pdf
                  asset_content_type: application/pdf
