name: Build PDF for Release

on:
    push:
        branches:
            - master # Only run on the master branch
        paths:
            - '**.tex' # Only run if the resume itself is updated
        tags-ignore:
            - nochange**   # Do not build a new version for any commit tagged with a tag that starts with nochange
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y texlive-xetex

            - name: Build Document
              run: xelatex Gabriel_Roper_Resume.tex

            - name: Get Current DateTime
              id: getdate
              run: echo "::set-output name=dtVal::$(date +'%Y-%m-%d_%H.%M')"

            - name: Create Release
              uses: softprops/action-gh-release@v2
              id: create_release
              with:
                  files: Gabriel_Roper_Resume.pdf
                  name: Resume ${{steps.getdate.outputs.dtVal}}
                  tag_name: ${{steps.getdate.outputs.dtVal}}
