name: Build PDF for Release

on:
    push:
        paths: 
            - '**.tex' # Only run if the resume itself is updated
        tags-ignore:
            - nochange**   # Do not build a new version for any commit tagged with a tag that starts with nochange
    workflow_dispatch:
        
                
            

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y texlive-xetex
            - name: Build Document
              run: xelatex Gabriel_Roper_Resume.tex

            - name: Get Current DateTime
              id: getdate
              run: echo "::set-output name=dtVal::$(date +'%Y-%m-%d_%H.%M')"

            - name: Create Release
              uses: softprops/action-gh-release@v0.1.13
              if: ${{ github.ref == 'refs/heads/master' }}
              with:
                  files: Gabriel_Roper_Resume.pdf
