name: Check For Errors
on:
    push:
        branches-ignore:            # Do not check against the master branch, as this is already checked by the build and deploy script
            - master
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2.0.0

            - name: Install Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y texlive-xetex
            - name: Build and Check Document
              run: xelatex Resume.tex


